# Generated by Django 4.2.30 on 2026-08-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Water', 'Water'), ('Electricity', 'Electricity'), ('Internet/WiFi', 'Internet/WiFi'), ('Infrastructure', 'Infrastructure'), ('Classroom', 'Classroom'), ('Laboratory', 'Laboratory'), ('Hostel', 'Hostel'), ('Canteen', 'Canteen'), ('Transport', 'Transport'), ('Cleanliness', 'Cleanliness'), ('Safety', 'Safety'), ('Other', 'Other')], default='Other', max_length=50)),
                ('ai_predicted_category', models.CharField(blank=True, choices=[('Water', 'Water'), ('Electricity', 'Electricity'), ('Internet/WiFi', 'Internet/WiFi'), ('Infrastructure', 'Infrastructure'), ('Classroom', 'Classroom'), ('Laboratory', 'Laboratory'), ('Hostel', 'Hostel'), ('Canteen', 'Canteen'), ('Transport', 'Transport'), ('Cleanliness', 'Cleanliness'), ('Safety', 'Safety'), ('Other', 'Other')], max_length=50, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('ai_predicted_priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Approval'), ('APPROVED', 'Approved / Public'), ('Open', 'Open'), ('Under Review', 'Under Review'), ('Solution Available', 'Solution Available'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='problem_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_problems', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='problems.problem')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
