# Generated by Django 4.2.30 on 2026-08-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('admin_decision', models.CharField(choices=[('PENDING', 'Pending'), ('DUPLICATE', 'Duplicate'), ('MERGE', 'Merge'), ('SEPARATE', 'Keep Separate')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_records', to='problems.problem')),
                ('similar_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_records', to='problems.problem')),
            ],
        ),
    ]
