# Generated by Django 4.2.30 on 2026-08-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0001_initial'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE_PROBLEM', 'Approve Problem'), ('REJECT_PROBLEM', 'Reject Problem'), ('EDIT_PROBLEM', 'Edit Problem'), ('MERGE_PROBLEM', 'Merge Problem'), ('APPROVE_SOLUTION', 'Approve Solution'), ('REJECT_SOLUTION', 'Reject Solution'), ('MARK_RECOMMENDED', 'Mark Recommended'), ('ARCHIVE_SOLUTION', 'Archive Solution')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solutions.solution')),
            ],
        ),
    ]
